### ISSUE TITLE
Improve HL7 error location support

### ISSUE THREAD

**Issue by michellefbarber** [immregistries/mqe#13]
[OVERVIEW]
The HL7 Error location (ERR-2) contains the position where an issue is   found. DQA does show some of this location but doesn't include enough   information to pinpoint the exact location. This task is to ensure the exact location   is always identified when an issues is associated with a specific   location.            

[REQUIREMENTS]
For each sub field in the ERL data type the following work should be   done:      
* Segment ID: Working correctly now for most issues, no   change here.       
* Segment Sequence: Only showing 1, should link to the segment as it appears   in the message. (1 for the first RXA, 2 for the second RXA, etc.) Ideally   this should be set when parsing the data coming in.       * Field Position: Working correctly now for most issues, no change   here.      
* Field Repetition: This does not have to be supported yet, not much   validation is being done in repetitions.       
* Component Number:   This should be supported, if it isn't already      
* Sub-Component Number: We have no issues at this level, for now this does   not need to be implemented.

[DEV NOTES]
The best option would be to store   where each field of data was pulled from, but this might be too much. The   next best option is just to store a position with major objects. For example   on a NK1 or Vaccination object simply indicate it's ordinal number, ensuring   it matches with what was in the message. That way when the issues is   generated we can pull that number back out and pass to ERR segment.  

[TESTING]
Testing for this will be done by the AART project.

**Comment by michellefbarber** [comment]
16/Mar/17 12:07   PM;admin;Not complete. Some  changes   were made to the ERR segment but the location was not improved.

**Comment by michellefbarber** [comment]
Duplicate of Issue #42 (has since been deleted). Identified after Issue #41 was resolved.

This bug was found...
ACK message needs to always have location when referring to issue at a specific place.

**Comment by nathanbunker** [comment]
Running this message: 
`MSH|^~\&||1255-60-20|MCIR|MDCH|20180420090949-0600||VXU^V04^VXU_V04|3WzJ-A.01.01.2aF|T|2.5.1|
PID|||3WzJ-A.01.01-1756907530^^^AIRA-TEST^MR||Koorong^Unaiza^^^^^L|Bayanai^Tivona|20180101|M||2076-8^Native Hawaiian or Other Pacific Islander^HL70005|417 Bridge St NW^^Grand Rapids^MI^49544^USA^P||^PRN^PH^^^616^9245843|||||||||2135-2^Hispanic or Latino^HL70005|Birth Place PID-23|||
PD1|||||||||||02^Reminder/Recall - any method^HL70215|||||A|20170301|20170301|
NK1|1|Koorong^Tivona^^^^^L|MTH^Mother^HL70063|81 Page Pl^^GR^MI^49544^USA^P|^PRN^PH^^^616^9245843|
ORC|RE||V51L2.3^AIRA|||||||I-23432^Burden^Donna^A^^^^^NIST-AA-1||57422^RADON^NICHOLAS^^^^^^NIST-AA-1^L|
RXA|0|1|20180401||21^Varicella^CPOP|0.5|mL^milliliters^UCUM||00^Administered^NIP001||||||Y5841RR||MSD^Merck and Co^MVX||||A|
RXR|SC^^HL70162|RA^^HL70163|
OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V02^VFC eligible - Medicaid/Medicaid Managed Care^HL70064||||||F|||20170301|||VXC40^Eligibility captured at the immunization level^CDCPHINVS|
OBX|2|CE|30956-7^Vaccine Type^LN|2|21^Varicella^CVX||||||F|
OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20080313||||||F|
OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20170301||||||F|
ORC|RE||BQ61L11032.2^AIRA|||||||I-23432^Burden^Donna^A^^^^^NIST-AA-1||57422^RADON^NICHOLAS^^^^^^NIST-AA-1^L
RXA|0|1|20180401||66019-0302-XX^FluMist Quadrivalent^NDC|0.5|Gallons^milliliters^UCUM||00^Administered^NIP001||||||N3783EO||MED^^MVX|||CP|A`

I get this response:
`MSH|^~\&|MQE Message Hub App|MQE Facility||1255-60-20|20180420091045-0600||ACK^V04^ACK|20180420091045-0600.3|P|2.5.1|||NE|NE|||||Z23^CDCPHINVS|
MSA|AE|3WzJ-A.01.01.2aF|
ERR||RXA^1^5^1|101^Required field missing^HL70357|E|4^Invalid value^HL70533^MQE0244^Vaccination admin code is missing^L|||Vaccination admin code is missing null|
ERR||RXA^2^5^1|103^Table value not found^HL70357|E|4^Invalid value^HL70533^MQE0247^Vaccination admin code is unrecognized^L|||Vaccination admin code is unrecognized null|
ERR||RXA^2^5^1|0^Message accepted^HL70357|E|4^Invalid value^HL70533^MQE0561^Vaccination admin code is not usable^L|||Vaccination admin code is not usable null|
ERR||RXA^2^5^1^1|103^Table value not found^HL70357|W|4^Invalid value^HL70533^MQE0559^Vaccination NDC code is unrecognized^L|||Vaccination NDC code is unrecognized null|
ERR||RXA^2^7^1|103^Table value not found^HL70357|W|4^Invalid value^HL70533^MQE0450^Vaccination administered unit is unrecognized^L|||Vaccination administered unit is unrecognized null|
ERR|||101^Required field missing^HL70357|I|4^Invalid value^HL70533^MQE0542^Vaccination VIS is missing^L|||Vaccination VIS is missing null|`

It looks like this issue is already fixed.
